/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    InstagramFeed: typeof import('./src/components/InstagramFeed.vue')['default']
    Layer1: typeof import('./src/components/Layer1.vue')['default']
    Layer2: typeof import('./src/components/Layer2.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RegisterBar: typeof import('./src/components/RegisterBar.vue')['default']
    RegisterBL: typeof import('./src/components/RegisterBL.vue')['default']
    RegisterBR: typeof import('./src/components/RegisterBR.vue')['default']
    RegisterTL: typeof import('./src/components/RegisterTL.vue')['default']
    RegisterTR: typeof import('./src/components/RegisterTR.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
